; Listing generated by Microsoft (R) Optimizing Compiler Version 19.14.26433.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\hsh6679\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
