#include "HCorePCH.h"
#include "HTypeOverrides.h"
#include "HReflectionContextImplementMacro.h"

IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(int8);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(int16);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(int32);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(int64);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(uint8);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(uint16);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(uint32);
IMPLEMENT_REFLECTION_CONTEXT_BASE_TYPE(uint64);